# Generated by Django 5.2.1 on 2025-05-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cca2', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name_common', models.CharField(max_length=255)),
                ('name_official', models.CharField(max_length=255)),
                ('capital', models.JSONField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.BigIntegerField(default=0)),
                ('languages', models.JSONField(blank=True, null=True)),
                ('timezones', models.JSONField(blank=True, null=True)),
                ('flags', models.JSONField(blank=True, null=True)),
                ('latlng', models.JSONField(blank=True, null=True)),
                ('borders', models.JSONField(blank=True, null=True)),
                ('currencies', models.JSONField(blank=True, null=True)),
                ('continents', models.JSONField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name_common'],
            },
        ),
    ]
